<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download_1</name>
   <tag></tag>
   <elementGuidId>720beb99-336d-4239-b1d3-a051d0d2fa13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>adebace6-9c7b-424d-8ec0-5bc3dae22ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NoticePdf/14May202415113568.pdf</value>
      <webElementGuid>9c154253-5142-4c5c-b41f-a3fb0c39030f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url</value>
      <webElementGuid>88ed1ab5-67eb-4d34-89a6-9feaad15b1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8d744a46-1f85-4a61-b5c9-c426e9dbf877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-success btn</value>
      <webElementGuid>fe3fc0e0-7032-4083-8965-9a842dd2f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Download</value>
      <webElementGuid>3d534165-1f85-4595-bfd8-3ba64ea88e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url&quot;)</value>
      <webElementGuid>7a9329a2-973c-4523-b706-767892e3a061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url']</value>
      <webElementGuid>1664695d-8f9e-497e-9a2a-a03fbea9164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[4]/section/div/div[3]/table/tbody/tr[5]/td[3]/a</value>
      <webElementGuid>f6ab2f53-ae17-4772-9050-f6e0a012636c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[9]</value>
      <webElementGuid>d9ed48b6-0159-4ffe-bee6-f50b5f8bb4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NoticePdf/14May202415113568.pdf')]</value>
      <webElementGuid>e6fcd549-236c-4c57-9d1a-768d3beb2763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/a</value>
      <webElementGuid>9cac2b7b-19b9-4695-a057-403444bb8ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'NoticePdf/14May202415113568.pdf' and @id = 'ctl00_ContentPlaceHolder1_rpEn_ctl04_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>570dc021-9906-44f8-858a-07db86e6b33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
