<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>4c15d1f2-caf4-4ae3-ba86-319c538d2be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45edf3ab-dbe0-45f0-bc74-898aea01f4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NoticePdf/11Jun202414095395.pdf</value>
      <webElementGuid>b8258b83-c5b6-4226-bed8-31a079c9694e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url</value>
      <webElementGuid>d1d539fa-667a-45ef-9328-42983e117529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cbd8ce9e-236c-44de-9977-467c3bef44af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-success btn</value>
      <webElementGuid>d2cb77c3-9c74-4c85-a24f-927e0c87a439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Download</value>
      <webElementGuid>25d10b9f-d042-4ea3-8413-1aef0eadfe41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url&quot;)</value>
      <webElementGuid>03d370f7-f60c-42f7-b778-2620e883e145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url']</value>
      <webElementGuid>a7c6e553-33f7-491c-b624-c1899f43961e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[4]/section/div/div[3]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>11801e70-6463-4fa8-a5c8-4d5174314233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[5]</value>
      <webElementGuid>6e525082-b54f-412a-b993-f7b544ddc5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::a[1]</value>
      <webElementGuid>4f98525b-eeac-4cdf-8246-f28697501ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heading'])[1]/following::a[1]</value>
      <webElementGuid>5e8a28b3-3847-43ff-993e-4a36a61cd7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NoticePdf/11Jun202414095395.pdf')]</value>
      <webElementGuid>adf96d20-5147-468a-90a7-b92b9eaacd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>374334f0-7fbf-4ebf-8aa8-6cbf4e310680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'NoticePdf/11Jun202414095395.pdf' and @id = 'ctl00_ContentPlaceHolder1_rpEn_ctl00_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>d488e494-c59b-4475-be4d-8e0239333227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
