<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpscm.bihar.gov.inusershome.aspx</name>
   <tag></tag>
   <elementGuidId>e4bc5a7f-61e3-4419-8653-dd120f2f8007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>center > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='aspnetForm']/div[4]/div/div/div[2]/center/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://cm.bihar.gov.in/users/home.aspx&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f30aee68-9ced-4e92-a974-774de3cffdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cm.bihar.gov.in/users/home.aspx</value>
      <webElementGuid>a7e27497-7301-4a93-a152-915ce2d02aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d71676c5-6d8b-4f68-823e-1dd76a0acea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://cm.bihar.gov.in/users/home.aspx</value>
      <webElementGuid>33685a6c-f065-4e2e-8693-231153f736bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/div[4]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/center[1]/a[1]</value>
      <webElementGuid>1414f611-d4ae-4a41-9ee3-10e616a654e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[4]/div/div/div[2]/center/a</value>
      <webElementGuid>8334d28a-ca91-4d47-814b-020bd7496e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://cm.bihar.gov.in/users/home.aspx')]</value>
      <webElementGuid>d3aa3a09-b43b-4a3b-a77c-cf971f7ace79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shri Nitish Kumar'])[1]/following::a[1]</value>
      <webElementGuid>e93f379a-6075-49a0-a54d-f1eaf654483a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bihar University of Health Sciences, Patna'])[1]/preceding::a[1]</value>
      <webElementGuid>67312b96-d1bd-4b08-88ab-0efe909eb9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estd.: 2022'])[1]/preceding::a[1]</value>
      <webElementGuid>3997494b-abf3-47fd-b48d-0044882a6560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://cm.bihar.gov.in/users/home.aspx']/parent::*</value>
      <webElementGuid>d6135083-3734-40c8-a96c-7a801c92bc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://cm.bihar.gov.in/users/home.aspx')]</value>
      <webElementGuid>7896f1b3-28c2-49ef-a625-ebe4da34fc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/a</value>
      <webElementGuid>e384b74d-4e93-40bc-aeb5-f637a610b90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cm.bihar.gov.in/users/home.aspx' and (text() = 'https://cm.bihar.gov.in/users/home.aspx' or . = 'https://cm.bihar.gov.in/users/home.aspx')]</value>
      <webElementGuid>41e81c82-5d2d-4088-8004-5bc6198851b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
