<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>e46e5c04-332a-4628-98d9-e6abe49161bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b047856-e794-4ebd-8375-ea2eba16cfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/BHUEDU/UploadedImage/Act_Image/doct2023102615539953.pdf</value>
      <webElementGuid>3148b649-80ae-4732-bdfe-c62e650fda2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url</value>
      <webElementGuid>7e36a3eb-96f9-425e-a888-8f724dfddc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e236434f-a31a-4701-9488-11e54af22c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-success btn</value>
      <webElementGuid>5967c7cb-a77e-4cfe-a2d0-0afc7641375e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Download</value>
      <webElementGuid>041970d6-96f8-4391-bceb-a0e7e4a03e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url&quot;)</value>
      <webElementGuid>151f37ee-df90-4345-bd44-29b213222794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url']</value>
      <webElementGuid>0c4d14ce-b49c-4027-ab08-dbd81e9bf06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_grdcollegeeng']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>030b2a4f-c8fa-4555-924f-c7b37586db00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[5]</value>
      <webElementGuid>d1feed2e-72d9-49b6-94d6-a722cf5076a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUHS ACT 2021'])[1]/following::a[1]</value>
      <webElementGuid>3a61f515-9426-4d5b-b574-2507ae332962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::a[1]</value>
      <webElementGuid>c9577685-4911-404f-b5e1-2feaf1aab310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Statute of BUHS'])[1]/preceding::a[1]</value>
      <webElementGuid>ef590e6b-1588-4478-a617-f49b8bc0314c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BHUEDU/UploadedImage/Act_Image/doct2023102615539953.pdf')]</value>
      <webElementGuid>e28535db-bdf5-4ce7-ad17-d289c7f99b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>2af11135-cd76-4858-99c8-7d30ff971867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BHUEDU/UploadedImage/Act_Image/doct2023102615539953.pdf' and @id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>ea0b172d-c8cb-4057-b0d6-1ad355766cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syllabus of Bachelor of Physiotherapy'])[1]/following::a[1]</value>
      <webElementGuid>d76de1d9-8cca-4b57-a77f-3e4b5047b703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Syllabus'])[3]/following::a[1]</value>
      <webElementGuid>6f2cfa70-466d-4182-b3a8-7e47684a75ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syllabus of Bachelor of Occupationaltherapy'])[1]/preceding::a[1]</value>
      <webElementGuid>d7be468b-eff1-4629-bab0-3180a1d6a6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/BHUEDU/UploadedImage/Syllabuspdf/doct202437123122857.pdf')]</value>
      <webElementGuid>e4f6a65e-e162-4999-910a-436f1abad926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/BHUEDU/UploadedImage/Syllabuspdf/doct202437123122857.pdf' and @id = 'ctl00_ContentPlaceHolder1_grdcollegeeng_ctl02_lnl_url' and (text() = '
                                             Download' or . = '
                                             Download')]</value>
      <webElementGuid>9c2579f0-cb6d-4eac-bec4-dee73bb27532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
