<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Key Contacts_img-responsive slide</name>
   <tag></tag>
   <elementGuidId>1b1a3b03-f85d-40e0-a5a8-112b126f87a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a > img.img-responsive.slide</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='clientlogo']/li[5]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#clientlogo > li:nth-child(5) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9b027fe-3f1c-4158-ae75-1f675d61d182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/cmrf.png</value>
      <webElementGuid>1afe4a1e-5b7f-40e5-bcf3-21f493a789a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive slide</value>
      <webElementGuid>197e9246-b0bd-4b27-b133-0241b43af346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientlogo&quot;)/li[5]/a[1]/img[@class=&quot;img-responsive slide&quot;]</value>
      <webElementGuid>9b983d14-d516-46c6-9091-05a137e6b7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='clientlogo']/li[5]/a/img</value>
      <webElementGuid>696e53cd-b623-439d-807e-c337dcd0d27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/img</value>
      <webElementGuid>7ce4141d-7e10-4237-b46b-018bb0402794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/cmrf.png']</value>
      <webElementGuid>5635bb65-396d-471d-8e22-2aad00310b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
